# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: etritest  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }} # set this to the path to your web app project
  JAVA_VERSION: '1.8'                # set this to the Java version to use
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_SECRET }}     # set GH repo secret with the publish profile of the web app
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml     
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: '${{env.AZURE_WEBAPP_NAME}}'
        path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.jar'
  
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    needs: build
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java', 'javascript', 'python' ] 
        #CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ] 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  
  deploy:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
    - name: download artifact
      uses: actions/download-artifact@v2
      with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
    - uses: actions/checkout@v2
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'
